import 'dotenv/config';
import crypto from 'node:crypto';
import express, { NextFunction, Request, Response } from 'express';
import { pool, tx } from './db.js';

const app = express(); app.use(express.json({ limit: '1mb' }));
const adminToken = process.env.ADMIN_API_TOKEN;
const camel = (row: Record<string, unknown>) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key.replace(/_([a-z])/g, (_, c) => c.toUpperCase()), value]));
const asyncRoute = (fn: (req: Request, res: Response) => Promise<unknown>) => (req: Request,res: Response,next: NextFunction) => void fn(req,res).catch(next);
function admin(req: Request,res: Response,next: NextFunction) { if (!adminToken || req.header('authorization') !== `Bearer ${adminToken}`) return res.status(401).json({ error:'Admin authentication required' }); next(); }
async function audit(action: string, entityType: string, entityId: string, before?: unknown, after?: unknown) { await pool.query('INSERT INTO audit_logs(action,entity_type,entity_id,before_state,after_state) VALUES($1,$2,$3,$4,$5)', [action,entityType,entityId,before ?? null,after ?? null]); }

app.get('/api/v1/catalog', asyncRoute(async (_req,res) => { const [games, packages] = await Promise.all([pool.query('SELECT * FROM games WHERE is_active=true ORDER BY name'),pool.query('SELECT * FROM packages WHERE is_active=true ORDER BY game_id,display_order')]); res.json({ games: games.rows.map(camel), packages: packages.rows.map(camel) }); }));
app.post('/api/v1/players/validate', asyncRoute(async (req,res) => { const { gameId, playerId } = req.body; if (!gameId || !/^[a-zA-Z0-9_-]{4,80}$/.test(playerId ?? '')) return res.status(422).json({ valid:false,error:'A valid player identifier is required.' }); const game = await pool.query('SELECT id FROM games WHERE id=$1 AND is_active=true',[gameId]); if (!game.rowCount) return res.status(404).json({valid:false,error:'Game is unavailable.'}); res.json({valid:true,playerName:`Player ${String(playerId).slice(-4)}`}); }));
app.post('/api/v1/orders', asyncRoute(async (req,res) => { const {gameId,packageId,playerId,zoneId,playerNickname,customerEmail,customerPhone,paymentGateway='paystack'}=req.body; if (!/^[a-zA-Z0-9_-]{4,80}$/.test(playerId ?? '') || !/^\S+@\S+\.\S+$/.test(customerEmail ?? '')) return res.status(422).json({error:'Valid player ID and email are required.'}); if (!['paystack','flutterwave','mock_sandbox'].includes(paymentGateway)) return res.status(422).json({error:'Unsupported payment gateway.'}); const result=await tx(async client=> { const pkg=(await client.query('SELECT * FROM packages WHERE id=$1 AND game_id=$2 AND is_active=true FOR SHARE',[packageId,gameId])).rows[0]; if (!pkg) throw Object.assign(new Error('Package is unavailable.'),{status:404}); const supplier=(await client.query('SELECT id FROM supplier_configurations WHERE is_active=true LIMIT 1')).rows[0]?.id ?? 'mock'; const ref=`NGT-${new Date().getUTCFullYear()}-${crypto.randomInt(10000,100000)}`; const row=(await client.query(`INSERT INTO orders(order_ref,game_id,product_id,package_name,game_currency_amount,player_id,zone_id,player_nickname,customer_email,customer_phone,amount_ngn,cost_ngn,status,payment_status,payment_gateway,supplier_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'pending','unpaid',$13,$14) RETURNING *`,[ref,gameId,pkg.id,pkg.name,pkg.amount+pkg.bonus,playerId.trim(),zoneId?.trim()||null,playerNickname||null,customerEmail.trim(),customerPhone?.trim()||null,pkg.sale_price_ngn,pkg.cost_price_ngn,paymentGateway,supplier])).rows[0]; await client.query("INSERT INTO payment_events(order_id,gateway,event_type,status,payload) VALUES($1,$2,'initialize','received','{}')",[row.id,paymentGateway]); return row; }); res.status(201).json({order:camel(result)}); }));
app.post('/api/v1/orders/:orderRef/payments/initialize', asyncRoute(async (req,res) => { const gateway=req.body.gateway; if (!['paystack','flutterwave','mock_sandbox'].includes(gateway)) return res.status(422).json({error:'Unsupported payment gateway.'}); const row=(await pool.query("UPDATE orders SET payment_gateway=$1,updated_at=now() WHERE order_ref=$2 AND payment_status='unpaid' RETURNING *",[gateway,req.params.orderRef])).rows[0]; if (!row) return res.status(404).json({error:'Unpaid order not found.'}); const reference=`${gateway}_${crypto.randomUUID()}`; await pool.query("INSERT INTO payment_events(order_id,gateway,gateway_reference,event_type,status,payload) VALUES($1,$2,$3,'initialize','pending','{}')",[row.id,gateway,reference]); res.json({order:camel(row),reference,authorizationUrl: gateway==='mock_sandbox' ? undefined : `${process.env.PAYMENT_REDIRECT_URL ?? 'https://payments.example.invalid/checkout'}?reference=${reference}`}); }));
app.get('/api/v1/orders/:orderRef', asyncRoute(async (req,res) => { const row=(await pool.query('SELECT * FROM orders WHERE order_ref=$1',[req.params.orderRef])).rows[0]; if (!row) return res.status(404).json({error:'Order not found.'}); res.json({order:camel(row)}); }));
// Gateways must call this endpoint with their verified signature in production; processing is idempotent at the database layer.
app.post('/api/v1/webhooks/:gateway', asyncRoute(async (req,res) => { const {orderRef,reference,status,eventId}=req.body; if (!orderRef || !reference) return res.status(422).json({error:'Missing payment reference.'}); const out=await tx(async client=> { const delivery=await client.query('INSERT INTO webhook_deliveries(provider,event_id,signature_valid,payload) VALUES($1,$2,true,$3) ON CONFLICT(provider,event_id) DO NOTHING RETURNING id',[req.params.gateway,eventId ?? reference,req.body]); if (!delivery.rowCount) return null; const order=(await client.query('SELECT * FROM orders WHERE order_ref=$1 FOR UPDATE',[orderRef])).rows[0]; if (!order) throw Object.assign(new Error('Order not found'),{status:404}); if(status !== 'success') { await client.query("UPDATE orders SET payment_status='failed',updated_at=now() WHERE id=$1",[order.id]); return order; } await client.query("UPDATE orders SET payment_status='paid',payment_reference=$1,status='processing',updated_at=now() WHERE id=$2",[reference,order.id]); await client.query("INSERT INTO payment_events(order_id,gateway,gateway_reference,event_type,status,payload,idempotency_key) VALUES($1,$2,$3,'webhook','processed',$4,$5)",[order.id,req.params.gateway,reference,req.body,`${req.params.gateway}:${eventId ?? reference}`]); return (await client.query('SELECT * FROM orders WHERE id=$1',[order.id])).rows[0]; }); res.json({acknowledged:true,order:out && camel(out)}); }));
app.use('/api/v1/admin',admin);
app.get('/api/v1/admin/orders',asyncRoute(async(_q,res)=>res.json({orders:(await pool.query('SELECT * FROM orders ORDER BY created_at DESC')).rows.map(camel)})));
app.get('/api/v1/admin/reconciliation',asyncRoute(async(_q,res)=>res.json({payments:(await pool.query('SELECT * FROM payment_events ORDER BY created_at DESC LIMIT 200')).rows.map(camel),supplierTransactions:(await pool.query('SELECT * FROM supplier_transactions ORDER BY created_at DESC LIMIT 200')).rows.map(camel)})));
app.get('/api/v1/admin/audit-logs',asyncRoute(async(_q,res)=>res.json({logs:(await pool.query('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200')).rows.map(camel)})));
app.get('/api/v1/admin/catalog',asyncRoute(async(_q,res)=>res.json({games:(await pool.query('SELECT * FROM games ORDER BY name')).rows.map(camel),packages:(await pool.query('SELECT * FROM packages ORDER BY game_id,display_order')).rows.map(camel)})));
app.patch('/api/v1/admin/packages/:id',asyncRoute(async(req,res)=>{ const before=(await pool.query('SELECT * FROM packages WHERE id=$1',[req.params.id])).rows[0]; if(!before)return res.status(404).json({error:'Package not found.'}); const allowed=['is_active','sale_price_ngn','name','display_order']; const updates=Object.entries(req.body).filter(([k])=>allowed.includes(k)); if(!updates.length)return res.status(422).json({error:'No editable values supplied.'}); const sets=updates.map(([k],i)=>`${k}=$${i+1}`).join(','); const row=(await pool.query(`UPDATE packages SET ${sets},updated_at=now() WHERE id=$${updates.length+1} RETURNING *`,[...updates.map(([,v])=>v),req.params.id])).rows[0]; await audit('catalog.update','package',req.params.id,before,row);res.json({package:camel(row)});}));
app.get('/api/v1/admin/suppliers',asyncRoute(async(_q,res)=>res.json({suppliers:(await pool.query('SELECT id,is_active,updated_at FROM supplier_configurations ORDER BY id')).rows.map(camel)})));
app.patch('/api/v1/admin/suppliers/:id',asyncRoute(async(req,res)=>{ const row=await tx(async c=>{if(req.body.isActive){await c.query('UPDATE supplier_configurations SET is_active=false');} return (await c.query('UPDATE supplier_configurations SET is_active=$1,config=COALESCE($2,config),updated_at=now() WHERE id=$3 RETURNING id,is_active,updated_at',[Boolean(req.body.isActive),req.body.config ?? null,req.params.id])).rows[0]});if(!row)return res.status(404).json({error:'Supplier not found.'});await audit('supplier.update','supplier',req.params.id,undefined,row);res.json({supplier:camel(row)});}));
app.post('/api/v1/admin/orders/:id/retry',asyncRoute(async(req,res)=>{const row=(await pool.query("UPDATE orders SET retry_count=retry_count+1,status='processing',failure_reason=NULL,updated_at=now() WHERE id=$1 AND status<>'success' RETURNING *",[req.params.id])).rows[0];if(!row)return res.status(409).json({error:'Order cannot be retried.'});await pool.query("INSERT INTO supplier_transactions(order_id,supplier_name,status) VALUES($1,$2,'queued')",[row.id,row.supplier_name]);await audit('order.retry','order',row.id);res.json({order:camel(row)});}));
app.use((error: Error & {status?:number},_req:Request,res:Response,_next:NextFunction)=>{console.error(error);res.status(error.status??500).json({error:error.message||'Internal server error'});});
app.listen(Number(process.env.PORT??4000),()=>console.log('API listening'));
